### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by GarimaKapoor** [minio-io/mc#364]
I get error "Permission denied", even if one file or folder under the tree is restricted.

C:\Users\Garima Kapoor\Documents>mc ls "c:\users\garima kapoor\documents"
open c:\users\garima kapoor\documents\My Music: Access is denied.
- 0 GK-X1CARBON2:mc/pkg/client/fs/fs.go:142 fs.(*fsClient).ListObjects(): {"sys.
arch":"amd64","sys.cpus":"4","sys.go":"go1.4.2","sys.host":"GK-X1CARBON2","sys.m
em.allocated":"212KB","sys.mem.heap.allocated":"950KB","sys.mem.heap.used":"129K
B","sys.mem.used":"129KB","sys.os":"windows"}

**Comment by fkautz** [comment]
Should be fixed with #367.

**Comment by fkautz** [comment]
Found another case where this shouldn't fail, reopening.
